import { Conversation, Stats } from "./types";

export const mockConversations: Conversation[] = [
  {
    id: "1",
    platform: "whatsapp",
    customerName: "Ahmet Yılmaz",
    customerAvatar: "AY",
    customerHandle: "+90 532 123 45 67",
    lastMessage: "Ürünleriniz hakkında bilgi alabilir miyim?",
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000),
    unreadCount: 3,
    status: "active",
    tags: ["teknik destek"],
    messages: [
      {
        id: "m1",
        conversationId: "1",
        content: "Merhaba, ürünleriniz hakkında bilgi alabilir miyim?",
        sender: "customer",
        timestamp: new Date(Date.now() - 20 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m2",
        conversationId: "1",
        content: "Özellikle endüstriyel ekipmanlarınızı merak ediyorum.",
        sender: "customer",
        timestamp: new Date(Date.now() - 15 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m3",
        conversationId: "1",
        content:
          "Tabii ki! Size yardımcı olmaktan memnuniyet duyarız. Hangi ekipman hakkında bilgi almak istiyorsunuz?",
        sender: "agent",
        timestamp: new Date(Date.now() - 10 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m4",
        conversationId: "1",
        content: "Ürünleriniz hakkında bilgi alabilir miyim?",
        sender: "customer",
        timestamp: new Date(Date.now() - 5 * 60 * 1000),
        status: "delivered",
        read: false,
      },
    ],
  },
  {
    id: "2",
    platform: "instagram",
    customerName: "Elif Kaya",
    customerAvatar: "EK",
    customerHandle: "@elifkaya_design",
    lastMessage: "Fiyat listesi gönderebilir misiniz?",
    lastMessageTime: new Date(Date.now() - 25 * 60 * 1000),
    unreadCount: 1,
    status: "active",
    tags: ["satış"],
    messages: [
      {
        id: "m5",
        conversationId: "2",
        content: "Merhaba! Ürünlerinizi Instagram'dan gördüm, harika görünüyor.",
        sender: "customer",
        timestamp: new Date(Date.now() - 45 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m6",
        conversationId: "2",
        content:
          "Teşekkür ederiz! Size nasıl yardımcı olabiliriz?",
        sender: "agent",
        timestamp: new Date(Date.now() - 40 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m7",
        conversationId: "2",
        content: "Fiyat listesi gönderebilir misiniz?",
        sender: "customer",
        timestamp: new Date(Date.now() - 25 * 60 * 1000),
        status: "delivered",
        read: false,
      },
    ],
  },
  {
    id: "3",
    platform: "messenger",
    customerName: "Mehmet Demir",
    customerAvatar: "MD",
    customerHandle: "Mehmet Demir",
    lastMessage: "Kurulum için ne kadar süre gerekiyor?",
    lastMessageTime: new Date(Date.now() - 60 * 60 * 1000),
    unreadCount: 0,
    status: "pending",
    tags: ["kurulum"],
    messages: [
      {
        id: "m8",
        conversationId: "3",
        content: "Merhaba, sistemin kurulumu ne kadar sürer?",
        sender: "customer",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m9",
        conversationId: "3",
        content:
          "Merhaba Mehmet Bey! Standart kurulum genellikle 2-3 iş günü içinde tamamlanır.",
        sender: "agent",
        timestamp: new Date(Date.now() - 90 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m10",
        conversationId: "3",
        content: "Kurulum için ne kadar süre gerekiyor?",
        sender: "customer",
        timestamp: new Date(Date.now() - 60 * 60 * 1000),
        status: "read",
        read: true,
      },
    ],
  },
  {
    id: "4",
    platform: "whatsapp",
    customerName: "Selin Arslan",
    customerAvatar: "SA",
    customerHandle: "+90 544 987 65 43",
    lastMessage: "Teşekkürler, çok yardımcı oldunuz!",
    lastMessageTime: new Date(Date.now() - 3 * 60 * 60 * 1000),
    unreadCount: 0,
    status: "resolved",
    tags: ["genel"],
    messages: [
      {
        id: "m11",
        conversationId: "4",
        content: "Ürün garantisi hakkında bilgi alabilir miyim?",
        sender: "customer",
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m12",
        conversationId: "4",
        content:
          "Ürünlerimiz 2 yıl garanti kapsamındadır. Herhangi bir sorun yaşarsanız 7/24 destek ekibimiz yanınızda.",
        sender: "agent",
        timestamp: new Date(Date.now() - 3.5 * 60 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m13",
        conversationId: "4",
        content: "Teşekkürler, çok yardımcı oldunuz!",
        sender: "customer",
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
        status: "read",
        read: true,
      },
    ],
  },
  {
    id: "5",
    platform: "instagram",
    customerName: "Can Öztürk",
    customerAvatar: "CÖ",
    customerHandle: "@can.ozturk",
    lastMessage: "Stoklarınızda var mı?",
    lastMessageTime: new Date(Date.now() - 4 * 60 * 60 * 1000),
    unreadCount: 2,
    status: "active",
    tags: ["stok sorgu"],
    messages: [
      {
        id: "m14",
        conversationId: "5",
        content: "Merhaba, XR-500 modeliniz stoklarınızda var mı?",
        sender: "customer",
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m15",
        conversationId: "5",
        content: "Stoklarınızda var mı?",
        sender: "customer",
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
        status: "delivered",
        read: false,
      },
    ],
  },
  {
    id: "6",
    platform: "messenger",
    customerName: "Zeynep Şahin",
    customerAvatar: "ZŞ",
    customerHandle: "Zeynep Şahin",
    lastMessage: "Teklif için ne zaman dönebilirsiniz?",
    lastMessageTime: new Date(Date.now() - 5 * 60 * 60 * 1000),
    unreadCount: 0,
    status: "pending",
    tags: ["teklif"],
    messages: [
      {
        id: "m16",
        conversationId: "6",
        content:
          "Toplu sipariş için özel fiyat alabilir miyiz? Yaklaşık 50 adet düşünüyoruz.",
        sender: "customer",
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
        status: "read",
        read: true,
      },
      {
        id: "m17",
        conversationId: "6",
        content: "Teklif için ne zaman dönebilirsiniz?",
        sender: "customer",
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
        status: "read",
        read: true,
      },
    ],
  },
];

export const mockStats: Stats = {
  totalMessages: 247,
  activeConversations: 12,
  resolvedToday: 38,
  avgResponseTime: "4.2 dk",
};

export const MOCK_USER = {
  username: "admin",
  password: "teknovateknik2025",
  name: "Teknovateknik Destek",
  role: "admin" as const,
  avatar: "TT",
};
